"""added bleaching alerts table

Revision ID: 082600a336ce
Revises: cc4307108000
Create Date: 2025-10-02 16:23:39.745438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '082600a336ce'
down_revision: Union[str, Sequence[str], None] = 'cc4307108000'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bleaching_alerts',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('location_name', sa.String(length=255), nullable=True),
    sa.Column('severity_level', sa.String(length=50), nullable=False),
    sa.Column('total_images_analyzed', sa.Integer(), nullable=False),
    sa.Column('bleached_count', sa.Integer(), nullable=False),
    sa.Column('average_bleaching_percentage', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('alert_threshold', sa.Integer(), nullable=False),
    sa.Column('first_detected_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('affected_coral_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('recommendations', sa.Text(), nullable=True),
    sa.Column('cluster_radius_km', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bleaching_alerts_is_active'), 'bleaching_alerts', ['is_active'], unique=False)
    op.create_index(op.f('ix_bleaching_alerts_latitude'), 'bleaching_alerts', ['latitude'], unique=False)
    op.create_index(op.f('ix_bleaching_alerts_longitude'), 'bleaching_alerts', ['longitude'], unique=False)
    op.create_index(op.f('ix_bleaching_alerts_severity_level'), 'bleaching_alerts', ['severity_level'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bleaching_alerts_severity_level'), table_name='bleaching_alerts')
    op.drop_index(op.f('ix_bleaching_alerts_longitude'), table_name='bleaching_alerts')
    op.drop_index(op.f('ix_bleaching_alerts_latitude'), table_name='bleaching_alerts')
    op.drop_index(op.f('ix_bleaching_alerts_is_active'), table_name='bleaching_alerts')
    op.drop_table('bleaching_alerts')
    # ### end Alembic commands ###
