"""added audit_trail table

Revision ID: 11edbfeb7afb
Revises: 90241595727e
Create Date: 2025-07-19 14:20:51.129675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11edbfeb7afb'
down_revision: Union[str, Sequence[str], None] = '90241595727e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_trail',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=False),
    sa.Column('actor_role', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('resource_type', sa.String(length=255), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_trail_on_actor_id', 'audit_trail', ['actor_id'], unique=False)
    op.create_index('idx_audit_trail_on_id', 'audit_trail', ['id'], unique=False)
    op.create_index('idx_audit_trail_on_resource_type', 'audit_trail', ['resource_type'], unique=False)
    op.create_index('idx_audit_trail_on_timestamp', 'audit_trail', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_audit_trail_on_timestamp', table_name='audit_trail')
    op.drop_index('idx_audit_trail_on_resource_type', table_name='audit_trail')
    op.drop_index('idx_audit_trail_on_id', table_name='audit_trail')
    op.drop_index('idx_audit_trail_on_actor_id', table_name='audit_trail')
    op.drop_table('audit_trail')
    # ### end Alembic commands ###
