"""added two more fields to analysis_result to store result from llm

Revision ID: 31ac4cf5a572
Revises: 4c5cccf2da45
Create Date: 2025-08-09 11:41:24.332534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31ac4cf5a572'
down_revision: Union[str, Sequence[str], None] = '4c5cccf2da45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_results', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('analysis_results', sa.Column('recommendations', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analysis_results', 'recommendations')
    op.drop_column('analysis_results', 'description')
    # ### end Alembic commands ###
