"""added necessary fields to users table

Revision ID: 45a90f78f390
Revises: ba3be1632c5c
Create Date: 2025-07-10 19:39:50.991383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45a90f78f390'
down_revision: Union[str, Sequence[str], None] = 'ba3be1632c5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', sa.String(length=100), nullable=False))
    op.add_column('users', sa.Column('last_name', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('contact_number', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('subscribe_to_newsletter', sa.Boolean(), server_default='false', nullable=True))
    op.add_column('users', sa.Column('city', sa.String(length=150), nullable=True))
    op.add_column('users', sa.Column('country', sa.String(length=150), nullable=True))
    op.add_column('users', sa.Column('birthdate', sa.Date(), nullable=False))
    op.add_column('users', sa.Column('bio', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('experience', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('diving_certification', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('research_experience', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('organization', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('primary_interests', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('users', sa.Column('contribution_types', sa.ARRAY(sa.String()), nullable=True))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=150),
               existing_nullable=False)
    op.drop_column('users', 'company')
    op.drop_column('users', 'name')
    op.drop_column('users', 'age')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('company', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.alter_column('users', 'email',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_column('users', 'contribution_types')
    op.drop_column('users', 'primary_interests')
    op.drop_column('users', 'organization')
    op.drop_column('users', 'research_experience')
    op.drop_column('users', 'diving_certification')
    op.drop_column('users', 'experience')
    op.drop_column('users', 'bio')
    op.drop_column('users', 'birthdate')
    op.drop_column('users', 'country')
    op.drop_column('users', 'city')
    op.drop_column('users', 'subscribe_to_newsletter')
    op.drop_column('users', 'contact_number')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###
