"""corrected typo

Revision ID: 4c5cccf2da45
Revises: c458e539910c
Create Date: 2025-07-27 12:55:14.674588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4c5cccf2da45'
down_revision: Union[str, Sequence[str], None] = 'c458e539910c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coral_images', sa.Column('observation_date', sa.DateTime(), nullable=True))
    op.drop_column('coral_images', 'observation_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coral_images', sa.Column('observation_data', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('coral_images', 'observation_date')
    # ### end Alembic commands ###
