"""change analysis_duration from Double to Float

Revision ID: 547da4ca3f7e
Revises: afdb41fba2d5
Create Date: 2025-07-15 12:55:34.023468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '547da4ca3f7e'
down_revision: Union[str, Sequence[str], None] = 'afdb41fba2d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
