"""added the field name on the coral image and archived data tables

Revision ID: 562be8ac39eb
Revises: 8d1d9742e90e
Create Date: 2025-08-18 14:43:14.560421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '562be8ac39eb'
down_revision: Union[str, Sequence[str], None] = '8d1d9742e90e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('archived_images', sa.Column('name', sa.String(length=255), nullable=True))
    op.add_column('coral_images', sa.Column('name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coral_images', 'name')
    op.drop_column('archived_images', 'name')
    # ### end Alembic commands ###
