"""removed unique constrainsts of provider for users

Revision ID: 60c5697e30f8
Revises: 45a90f78f390
Create Date: 2025-07-11 13:51:26.036937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60c5697e30f8'
down_revision: Union[str, Sequence[str], None] = '45a90f78f390'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('unique_provider_user'), 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('unique_provider_user'), 'users', ['provider', 'provider_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
