"""added a bleaching percentage field to analysis_result

Revision ID: 7c6d4cddee10
Revises: 893e15af9ea0
Create Date: 2025-08-12 16:47:24.362184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c6d4cddee10'
down_revision: Union[str, Sequence[str], None] = '893e15af9ea0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_results', sa.Column('bleaching_percentage', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analysis_results', 'bleaching_percentage')
    # ### end Alembic commands ###
