"""added default value to created_at and changed used_at nullable to true in verification token table

Revision ID: 8949d5ad07b5
Revises: b16c468f612d
Create Date: 2025-07-09 12:17:29.819059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8949d5ad07b5'
down_revision: Union[str, Sequence[str], None] = 'b16c468f612d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verification_tokens', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.alter_column('verification_tokens', 'used_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.create_index(op.f('ix_verification_tokens_used_at'), 'verification_tokens', ['used_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verification_tokens_used_at'), table_name='verification_tokens')
    op.alter_column('verification_tokens', 'used_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('verification_tokens', 'created_at')
    # ### end Alembic commands ###
