"""added a section field to website_content table

Revision ID: 8d1d9742e90e
Revises: 7c6d4cddee10
Create Date: 2025-08-14 21:13:48.799800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d1d9742e90e'
down_revision: Union[str, Sequence[str], None] = '7c6d4cddee10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('website_content', sa.Column('section', sa.String(length=50), nullable=True))
    op.create_index('idx_content_table_on_section', 'website_content', ['section'], unique=False)
    op.create_index(op.f('ix_website_content_section'), 'website_content', ['section'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_website_content_section'), table_name='website_content')
    op.drop_index('idx_content_table_on_section', table_name='website_content')
    op.drop_column('website_content', 'section')
    # ### end Alembic commands ###
