"""added a user id foreignkey to coral_images table

Revision ID: 8e480a75a7c0
Revises: 2579526c8502
Create Date: 2025-06-27 19:11:24.132744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e480a75a7c0'
down_revision: Union[str, Sequence[str], None] = '2579526c8502'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coral_images', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'coral_images', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'coral_images', type_='foreignkey')
    op.drop_column('coral_images', 'user_id')
    # ### end Alembic commands ###
