"""defined relationships between tables

Revision ID: 90241595727e
Revises: f88842ebfbeb
Create Date: 2025-07-17 12:27:51.790838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90241595727e'
down_revision: Union[str, Sequence[str], None] = 'f88842ebfbeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('analysis_results_image_id_fkey'), 'analysis_results', type_='foreignkey')
    op.create_foreign_key(None, 'analysis_results', 'coral_images', ['image_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('analytics_events_user_id_fkey'), 'analytics_events', type_='foreignkey')
    op.create_foreign_key(None, 'analytics_events', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('coral_images_user_id_fkey'), 'coral_images', type_='foreignkey')
    op.create_foreign_key(None, 'coral_images', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('password_reset_tokens_user_id_fkey'), 'password_reset_tokens', type_='foreignkey')
    op.create_foreign_key(None, 'password_reset_tokens', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('verification_tokens_user_id_fkey'), 'verification_tokens', type_='foreignkey')
    op.create_foreign_key(None, 'verification_tokens', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'verification_tokens', type_='foreignkey')
    op.create_foreign_key(op.f('verification_tokens_user_id_fkey'), 'verification_tokens', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'password_reset_tokens', type_='foreignkey')
    op.create_foreign_key(op.f('password_reset_tokens_user_id_fkey'), 'password_reset_tokens', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'coral_images', type_='foreignkey')
    op.create_foreign_key(op.f('coral_images_user_id_fkey'), 'coral_images', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'analytics_events', type_='foreignkey')
    op.create_foreign_key(op.f('analytics_events_user_id_fkey'), 'analytics_events', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'analysis_results', type_='foreignkey')
    op.create_foreign_key(op.f('analysis_results_image_id_fkey'), 'analysis_results', 'coral_images', ['image_id'], ['id'])
    # ### end Alembic commands ###
