"""modified users table to correct error

Revision ID: 9c8a93094e47
Revises: 0f5acb59c796
Create Date: 2025-07-07 15:21:43.352716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c8a93094e47'
down_revision: Union[str, Sequence[str], None] = '0f5acb59c796'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.create_index('idx_users_on_email', 'users', ['email'], unique=False)
    op.create_index('idx_users_on_id', 'users', ['id'], unique=False)
    op.create_index('idx_users_on_is_active', 'users', ['is_active'], unique=False)
    op.create_index('idx_users_on_provider', 'users', ['provider'], unique=False)
    op.create_index('idx_users_on_provider_id', 'users', ['provider_id'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index('idx_users_on_provider_id', table_name='users')
    op.drop_index('idx_users_on_provider', table_name='users')
    op.drop_index('idx_users_on_is_active', table_name='users')
    op.drop_index('idx_users_on_id', table_name='users')
    op.drop_index('idx_users_on_email', table_name='users')
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###
