"""added bleaching_percentage to archived data

Revision ID: a63a1a4873a2
Revises: 562be8ac39eb
Create Date: 2025-08-18 17:39:58.813315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a63a1a4873a2'
down_revision: Union[str, Sequence[str], None] = '562be8ac39eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('archived_images', sa.Column('bleaching_percentage', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('archived_images', 'bleaching_percentage')
    # ### end Alembic commands ###
