"""modified provider fields in user table

Revision ID: ae38372938c9
Revises: 5023a81fe9e7
Create Date: 2025-07-04 13:22:12.569153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae38372938c9'
down_revision: Union[str, Sequence[str], None] = '5023a81fe9e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'provider_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'provider_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
