"""dropped analysis_time field and replaced with analysis_duration

Revision ID: afdb41fba2d5
Revises: 31bcdd89fb66
Create Date: 2025-07-15 12:54:52.868444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'afdb41fba2d5'
down_revision: Union[str, Sequence[str], None] = '31bcdd89fb66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_results', sa.Column('analysis_duration', sa.Double(), nullable=True))
    op.drop_column('analysis_results', 'analysis_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_results', sa.Column('analysis_time', postgresql.TIME(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_column('analysis_results', 'analysis_duration')
    # ### end Alembic commands ###
