"""added latitude and longitude to coral_images table

Revision ID: ba3be1632c5c
Revises: 8949d5ad07b5
Create Date: 2025-07-10 10:55:07.094779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba3be1632c5c'
down_revision: Union[str, Sequence[str], None] = '8949d5ad07b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coral_images', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('coral_images', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coral_images', 'longitude')
    op.drop_column('coral_images', 'latitude')
    # ### end Alembic commands ###
