"""modified coral images table and added water depth, temperature and observation date

Revision ID: c458e539910c
Revises: 11edbfeb7afb
Create Date: 2025-07-27 12:53:04.961351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c458e539910c'
down_revision: Union[str, Sequence[str], None] = '11edbfeb7afb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coral_images', sa.Column('water_temperature', sa.String(length=124), nullable=True))
    op.add_column('coral_images', sa.Column('water_depth', sa.Float(), nullable=True))
    op.add_column('coral_images', sa.Column('observation_data', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coral_images', 'observation_data')
    op.drop_column('coral_images', 'water_depth')
    op.drop_column('coral_images', 'water_temperature')
    # ### end Alembic commands ###
