"""add bleaching alert table on alembic env

Revision ID: cc4307108000
Revises: df5c25358e4e
Create Date: 2025-09-30 15:44:15.924049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cc4307108000'
down_revision: Union[str, Sequence[str], None] = 'df5c25358e4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bleaching_alert',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('location_key', sa.String(length=250), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('area_name', sa.String(length=255), nullable=True),
    sa.Column('bleaching_count', sa.Integer(), nullable=False),
    sa.Column('severity_level', sa.String(length=20), nullable=False),
    sa.Column('alert_message', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=True),
    sa.Column('first_detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('alert_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bleaching_alert_is_active'), 'bleaching_alert', ['is_active'], unique=False)
    op.create_index(op.f('ix_bleaching_alert_last_updated_at'), 'bleaching_alert', ['last_updated_at'], unique=False)
    op.create_index(op.f('ix_bleaching_alert_location_key'), 'bleaching_alert', ['location_key'], unique=False)
    op.drop_index(op.f('idx_bleaching_alerts_active'), table_name='bleaching_alerts')
    op.drop_index(op.f('idx_bleaching_alerts_location'), table_name='bleaching_alerts')
    op.drop_index(op.f('idx_bleaching_alerts_severity'), table_name='bleaching_alerts')
    op.drop_index(op.f('idx_bleaching_alerts_updated'), table_name='bleaching_alerts')
    op.drop_table('bleaching_alerts')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bleaching_alerts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('location_key', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('area_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('bleaching_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('severity_level', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('alert_message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('first_detected_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('last_updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('resolved_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('bleaching_alerts_pkey'))
    )
    op.create_index(op.f('idx_bleaching_alerts_updated'), 'bleaching_alerts', ['last_updated_at'], unique=False)
    op.create_index(op.f('idx_bleaching_alerts_severity'), 'bleaching_alerts', ['severity_level'], unique=False)
    op.create_index(op.f('idx_bleaching_alerts_location'), 'bleaching_alerts', ['location_key'], unique=False)
    op.create_index(op.f('idx_bleaching_alerts_active'), 'bleaching_alerts', ['is_active'], unique=False)
    op.drop_index(op.f('ix_bleaching_alert_location_key'), table_name='bleaching_alert')
    op.drop_index(op.f('ix_bleaching_alert_last_updated_at'), table_name='bleaching_alert')
    op.drop_index(op.f('ix_bleaching_alert_is_active'), table_name='bleaching_alert')
    op.drop_table('bleaching_alert')
    # ### end Alembic commands ###
