"""added website_content table

Revision ID: d3c8edde14b1
Revises: 60c5697e30f8
Create Date: 2025-07-12 17:06:00.654654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3c8edde14b1'
down_revision: Union[str, Sequence[str], None] = '60c5697e30f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('website_content',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_content_table_on_content', 'website_content', ['content'], unique=False)
    op.create_index('idx_content_table_on_title', 'website_content', ['title'], unique=False)
    op.create_index('idx_website_content_on_id', 'website_content', ['id'], unique=False)
    op.create_index(op.f('ix_website_content_content'), 'website_content', ['content'], unique=False)
    op.create_index(op.f('ix_website_content_id'), 'website_content', ['id'], unique=False)
    op.create_index(op.f('ix_website_content_title'), 'website_content', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_website_content_title'), table_name='website_content')
    op.drop_index(op.f('ix_website_content_id'), table_name='website_content')
    op.drop_index(op.f('ix_website_content_content'), table_name='website_content')
    op.drop_index('idx_website_content_on_id', table_name='website_content')
    op.drop_index('idx_content_table_on_title', table_name='website_content')
    op.drop_index('idx_content_table_on_content', table_name='website_content')
    op.drop_table('website_content')
    # ### end Alembic commands ###
