"""add_alert_subscriptions_and_history_tables

Revision ID: e00983815d9b
Revises: 93b932eb0e8a
Create Date: 2025-09-29 16:10:16.852843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e00983815d9b'
down_revision: Union[str, Sequence[str], None] = '93b932eb0e8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
