"""create_public_bleaching_alerts_tables

Revision ID: ebb033ca0ab4
Revises: 6e136e79d766
Create Date: 2025-09-29 20:47:36.693847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebb033ca0ab4'
down_revision: Union[str, Sequence[str], None] = '6e136e79d766'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
