"""added a cascade to delete on verification_tokens table

Revision ID: f88842ebfbeb
Revises: 547da4ca3f7e
Create Date: 2025-07-16 14:54:44.782392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f88842ebfbeb'
down_revision: Union[str, Sequence[str], None] = '547da4ca3f7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
