"""corrected field name spelling of one field in analysis_results table

Revision ID: fc5ef1ba92c4
Revises: d3c8edde14b1
Create Date: 2025-07-15 12:15:04.244444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc5ef1ba92c4'
down_revision: Union[str, Sequence[str], None] = 'd3c8edde14b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_results', sa.Column('confidence_score', sa.Float(), nullable=True))
    op.drop_column('analysis_results', 'condifence_score')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_results', sa.Column('condifence_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('analysis_results', 'confidence_score')
    # ### end Alembic commands ###
